zuul:
  routes:
    got:
      path: /got/**
      url: http://www.mocky.io/v2/5cb6b0c13200003c12cd453f
    friends:
      path: /friends/**
      url: http://www.mocky.io/v2/5cb6b0cf3200003c12cd4541


server:
  port: 8080





